### ISSUE TITLE
error with all betas positive

### ISSUE THREAD

**Issue by crsl4** [joshday/SparseRegression.jl#13]
I was trying to code cross validation, when I realized that no matter which subset of the data I selected, I would always get all betas positive.
This could be a bug in the optimization?
I don't get the same results when I run with `GLMNet`.

```julia
using DataFrames, SparseRegression
dat = readtable("test.txt", header=true)
y = convert(Array{Float64,1},dat[:,1]) ##1st column: response
X = convert(Array{Float64,2},dat[:,2:end]) ##10,000 SNPs
obs = Obs(X, y)
s = SModel(obs, LogisticRegression(), L1Penalty())
@time learn!(s, ProxGrad(obs,0.001), MaxIter(10000), Converged(coef))
#23.880103 seconds (106.87 k allocations: 765.675 MiB, 0.69% gc time)
#SparseRegression.SModel{LossFunctions.LogitMarginLoss,PenaltyFunctions.L1Penalty}
 #> β        : [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
 #> λ factor : [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1  …  0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
 #> Loss     : LogitMarginLoss
 #> Penalty  : L1Penalty
find(x -> x != 0,s.β) ##103 SNPs for λ=0.1
mean(s.β[find(x -> x != 0,s.β)])
find(x -> x < 0,s.β) ## 0
```

Using  `GLMNet`:

```julia
using GLMNet, Distributions
y1 = Bool.(y)
y2 = .!y1
yy = [y1 y2]
path = @time glmnet(X, convert(Matrix{Float64}, yy), Binomial())
```
In `GLMNet`, the biggest lambda used is 0.089, and with this lambda, all betas are equal to 0 (no covariates in the model). `SparseRegression` is using lambda=0.1 (even bigger lambda), so I would expect all betas to be close to zero (but the mean is equal to 0.013, not that close to zero).
Could there by any rounding error somewhere, or something, making these estimated coefficients further from zero?

When trying with a different lambda (the best lambda by CV in `GLMNet` which yields 19 covariates in the model), we still get all positive betas for 170 covariates:

```julia
cv = @time glmnetcv(X, yy, Binomial())
#11.709583 seconds (299.73 k allocations: 623.351 MiB, 1.03% gc time)
#Logistic GLMNet Cross Validation
#100 models for 10000 predictors in 10 folds
#Best λ 0.062 (mean loss 1.380, std 0.008)
obs = Obs(X, y)
s = SModel(obs, LogisticRegression(), L1Penalty(), fill(0.062,size(X,2)))
@time learn!(s, ProxGrad(obs,0.001), MaxIter(10000), Converged(coef))
find(x -> x != 0,s.β) ##170 SNPs for λ=0.1
mean(s.β[find(x -> x != 0,s.β)])
find(x -> x < 0,s.β) ## 0
```
I attach a test data file to reproduce the error.
[test.txt](https://github.com/joshday/SparseRegression.jl/files/1349500/test.txt)

**Comment by joshday** [comment]
I think this is just because GLMNet parameterizes lambda differently.  I'm not sure how, but I remember getting SparseRegression results to match Convex but not GLMNet.

**Comment by crsl4** [comment]
Thanks Josh! Although I still believe it is strange that all the estimated betas are positive, regardless of the subset that I am taking. With the big number of covariates, all positive betas mean that in the prediction step of cross validation, we will always predict a value of 1. I checked with Lasso as well, and I got different results. I will check with Convex. If you learn something, let me know, thanks!

**Comment by joshday** [comment]
I think this is the issue:  Your `y` vector should only take values -1 and 1.  `LogisticRegression` is just an alias for `LogitMarginLoss` in LossFunctions (`MarginLoss` types have targets of -1 or 1).

```
help?> LogisticRegression
search: LogisticRegression

  LogitMarginLoss <: MarginLoss

  The margin version of the logistic loss. It is infinitely many times differentiable, strictly convex, and
  Lipschitz continuous.

  L(a) = \ln (1 + e^{-a})

  ----------------------------------------------------------------------------------------------------------

                Lossfunction                     Derivative
        ┌────────────┬────────────┐      ┌────────────┬────────────┐
      2 │ \.                      │    0 │                  ._--/""│
        │   \.                    │      │               ../'      │
        │     \.                  │      │              ./         │
        │       \..               │      │            ./'          │
      L │         '-_             │   L' │          .,'            │
        │            '-_          │      │         ./              │
        │               '\-._     │      │      .,/'               │
      0 │                    '""*-│   -1 │__.--''                  │
        └────────────┴────────────┘      └────────────┴────────────┘
        -2                        2      -4                        4
                   y ⋅ ŷ                            y ⋅ ŷ
```

**Comment by joshday** [comment]
The `a` in the equation above stands for agreement, which for a linear predictor is `y * x'beta`

**Comment by crsl4** [comment]
Thanks! Changing my response y from 0,1 to -1,1 fixed the issue. Thanks for your help!
