### ISSUE TITLE
Problem with example

### ISSUE THREAD

**Issue by patwa67** [joshday/SparseRegression.jl#6]
The Quick example no longer works. It used to do so.

**Comment by joshday** [comment]
There was a breaking change introduced to PenaltyFunctions.jl and I've irresponsibly left master in a half-rewritten state, as I got busy after I started breaking things.  I've been meaning to get this back up and running, so this issue will give me the push to get it fixed today 👍

**Comment by joshday** [comment]
Made some changes and updated the example.  The API will still probably go through another iteration or two before it gets settled.

**Comment by patwa67** [comment]
Well, I cannot get it to work (with another example):
```
using SparseRegression
nobs = 1000
nvar = 50000
x = randn(nobs,nvar)
y = sum(x[:,1:3],2).+sum(-x[:,4:5],2) .+ randn(nobs)*0.1
o = SparseReg(nvar; loss = L1DistLoss(), penalty = L2Penalty())
@time fit!(o, x, y, PROXGRAD(verbose = true))
```

**Comment by joshday** [comment]
I immediately started breaking things again.  I'll need a few days to sort out a few things.

**Comment by joshday** [comment]
I've got things sorted out.  I'll write up some actual documentation soon, but the README example works now.

**Comment by patwa67** [comment]
I'm using Julia 0.5.1 and there seems to be some problems with that:
WARNING: julia is fixed at 0.5.1 conflicting with requirement for SparseRegression: [0.6.0-,∞)
WARNING: julia is fixed at 0.5.1 conflicting with requirement for PenaltyFunctions: [0.6.0-,∞)

and when I try to load SparseRegression I get errors related to PenaltyFunctions:
ERROR: LoadError: syntax: expected identifier after "const"
 in include_from_node1(::String) at .\loading.jl:488
 in macro expansion; at .\none:2 [inlined]
 in anonymous at .\<missing>:?
 in eval(::Module, ::Any) at .\boot.jl:234
 in process_options(::Base.JLOptions) at .\client.jl:242
 in _start() at .\client.jl:321
while loading C:\Users\pawn0002\.julia\v0.5\PenaltyFunctions\src\PenaltyFunctions.jl, in expression starting on line 28

**Comment by joshday** [comment]
I changed SparseReg to require Julia 0.6-.

I was also a bit early on saying I have things sorted out, because I started breaking things again last night.  Sorry, I won't add noise to this issue again until I have things up and running and have documentation to show.

**Comment by joshday** [comment]
Things are in a good, stable place now.

**Comment by patwa67** [comment]
Dear Josh,

I saw that you have an issue with max lambda associated to
SparseRegression. There is a relatively easy way to implement an adaptive
learning rate that would fit well with fista and proxgrad. Let me know if
you would like some details. I didn't want to discuss this as an issue on
Github since I'm in the process of writing a paper. I don't know if you
would like to contribute to that, but if you want to it is fine with me.

Best regards,

Patrik Waldmann
Swedish University of Agricultural Sciences
Uppsala
Sweden

Den 2 maj 2017 4:33 em skrev "Josh Day" <notifications@github.com>:

Things are in a good, stable place now.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/joshday/SparseRegression.jl/issues/6#issuecomment-298653468>,
or mute the thread

**Comment by joshday** [comment]
I don't think I completely follow what you're saying.  If you want to contact me privately, you can email me at emailjoshday@gmail.com
